//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RunClub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Distance
    {
        public int DistanceID { get; set; }
        public string FullName { get; set; }
        public Nullable<double> DistanceCompleted { get; set; }
        public string WalkOrRun { get; set; }
        public string Time { get; set; }
    }
}
